chores (#39)
- feat: the updating of ananta now write to the .ananta_version file, so
it can trigger the release action to make a new release
- Updated project metadata to include separate homepage, source, and
issues URLs.
- Simplified and enhanced workflow files for better flexibility and
security by adjusting permissions and branch filters.

diff --git a/.github/workflows/ananta.yml b/.github/workflows/ananta.yml
--- a/.github/workflows/ananta.yml
+++ b/.github/workflows/ananta.yml
@@ -1,18 +1,17 @@
 name: ananta Image CI
 permissions:
   contents: write
-  packages: write
   id-token: write
 
 on:
   push:
-    branches:
-    - 'master'
+    branches: [ "master" ]
     paths:
     - '.github/workflows/ananta.yml'
     - 'script/dummy_ananta.sh'
     - 'sshconfig_to_ananta/**'
     - 'tests/**'
+    - '.ananta_version'
     - '.dockerignore'
     - 'docker-entrypoint.sh'
     - 'Dockerfile'
@@ -23,9 +22,13 @@ on:
     - '.github/workflows/ananta.yml'
     - 'script/dummy_ananta.sh'
     - 'sshconfig_to_ananta/**'
-    - '!sshconfig_to_ananta/test_**'
+    - 'tests/**'
+    - '.ananta_version'
+    - '.dockerignore'
     - 'docker-entrypoint.sh'
     - 'Dockerfile'
+    - 'pdm.lock'
+    - 'pyproject.toml'
   schedule:
   - cron: "0 5 1-31/10 * *"
   workflow_dispatch:
@@ -59,19 +62,6 @@ jobs:
           CACHED_GITHUB_API: ${{ secrets.GH_API_BASEURL }}
         run: |
           set -e -o pipefail
-          TMP_FILE=$(mktemp)
-          if curl --fail --silent --show-error --location --include --head \
-              --header "Accept: application/vnd.github.v3+json" --output "$TMP_FILE" -- \
-              "${CACHED_GITHUB_API}"; then
-
-              HTTP_STATUS_CODE=$(awk 'NR==1 {print $2}' "$TMP_FILE")
-              if [[ $HTTP_STATUS_CODE -ge 200 ]] && [[ $HTTP_STATUS_CODE -le 299 ]]; then
-                  echo "info: github cache is ready. will connect to the cached API instead of the default one"
-                  GITHUB_API_BASEURL="${CACHED_GITHUB_API}"
-              fi
-          fi
-          : "${GITHUB_API_BASEURL:="https://api.github.com"}"
-          "rm" -f "$TMP_FILE"
 
           ver_anata_helper=$(yq -r '.project.version' pyproject.toml | tr -d '\r\n\t\f\v ')
           if [[ "${{ github.event_name }}" == "pull_request" ]]; then
@@ -79,13 +69,11 @@ jobs:
               ver_anata_helper='dev'
           fi
 
-          ananta_latest_tag_name=$(
-              curl -sSL --fail --retry 5 --retry-delay 10 --retry-max-time 60 \
-                  -H 'Accept: application/vnd.github.v3+json' \
-                  "${GITHUB_API_BASEURL}/repos/cwt/ananta/releases/latest" \
-                  | jq -r .tag_name
-          )
-          ver_ananta="${ananta_latest_tag_name##v}"
+          if [[ ! -s .ananta_version ]]; then
+              echo "ERROR: .ananta_version file not found or is empty"
+              exit 1
+          fi
+          ver_ananta=$(tr -d '\r\n\t\f\v ' < .ananta_version)
           ver_anata_helper="v${ver_anata_helper}-${ver_ananta}"
 
           echo "ver_anata_helper=${ver_anata_helper}" >> "$GITHUB_OUTPUT"
@@ -150,7 +138,7 @@ jobs:
       -
         name: Build and push
         uses: docker/build-push-action@14487ce63c7a62a4a324b0bfb37086795e31c6c1 # v6
-        if: ${{ github.ref == 'refs/heads/master' }}
+        if: github.event.repository.default_branch == github.ref_name
         with:
           build-args: |
             ver_anata_helper=${{ steps.chores.outputs.ver_anata_helper }}
@@ -167,7 +155,7 @@ jobs:
       -
         name: Release
         uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631 # v2
-        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
+        if: github.event_name == 'push' && github.event.repository.default_branch == github.ref_name
         with:
           fail_on_unmatched_files: true
           generate_release_notes: true
